export enum ActionTypes {
  FETCH_CATS_START = 'FETCH_CATS_START',
  FETCH_CATS_SUCCESS = 'FETCH_CATS_SUCCESS',
  FETCH_CATS_FAILURE = 'FETCH_CATS_FAILURE',

  FETCH_MORE_CATS_START = 'FETCH_MORE_CATS_START',
  FETCH_MORE_CATS_SUCCESS = 'FETCH_MORE_CATS_SUCCESS',
  FETCH_MORE_CATS_FAILURE = 'FETCH_MORE_CATS_FAILURE',

  TOGGLE_IS_ZOOMED = 'TOGGLE_IS_ZOOMED',
}
